# Generated by Django 4.2.6 on 2023-10-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='lista_categorias',
        ),
        migrations.AddField(
            model_name='servicio',
            name='lista_trabajadores',
            field=models.ManyToManyField(to='api.trabajador'),
        ),
    ]
