# Generated by Django 4.2.6 on 2023-10-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_servicio_lista_categorias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha_tecnica',
            name='lista_areas_y_trabajdores_para_la_ficha_tecnica',
        ),
        migrations.DeleteModel(
            name='areas_y_trabajdores_para_la_ficha_tecnica',
        ),
    ]
